const api = '../api/index.php?action=';
let csrf = '', content = { events: [], media: [] };
const $ = selector => document.querySelector(selector);
const escape = value => String(value || '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
async function request(action, options = {}) {
  const response = await fetch(api + action, { credentials: 'same-origin', ...options, headers: { ...(options.headers || {}), ...(csrf ? { 'X-CSRF-Token': csrf } : {}) } });
  const json = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(json.error || 'Une erreur est survenue.');
  return json;
}
function format(date) { return new Intl.DateTimeFormat('fr-FR', { dateStyle: 'medium' }).format(new Date(`${date}T12:00:00`)); }
function render() {
  $('#events').innerHTML = [...content.events].sort((a,b) => a.startDate.localeCompare(b.startDate)).map(item => `<article class="event"><div><strong>${escape(format(item.startDate))}${item.endDate ? ` — ${escape(format(item.endDate))}` : ''}</strong><p>${escape(item.titleFr)} — ${escape(item.detailsFr)}</p><p>${item.type === 'residence' ? 'Résidence' : 'Diffusion'}${item.featured ? ' - À venir' : ''}</p></div><div><button data-edit="${item.id}" class="secondary">Modifier</button> <button data-delete="${item.id}" class="danger">Supprimer</button></div></article>`).join('') || '<p>Aucune date.</p>';
  $('#media').innerHTML = content.media.map(item => `<div><img src="${escape(item.url)}" alt=""><code>${escape(location.origin + item.url)}</code></div>`).join('') || '<p>Aucune photo ajoutée.</p>';
  $('#creations-admin').innerHTML = (content.creations || []).map(item => `<article class="event"><div><strong>${escape(item.titleFr)}</strong><p>${escape(item.metaFr)}</p></div><div><button data-creation-edit="${escape(item.id)}" class="secondary">Modifier</button> <button data-creation-delete="${escape(item.id)}" class="danger">Supprimer</button></div></article>`).join('') || '<p>Aucune création.</p>';
  $('#shared-form [name=collectivePhotos]').value = (content.collectivePhotos || []).join('\n');
  $('#shared-form [name=mediationHosts]').value = (content.mediationHosts || []).join('\n');
}
async function load() { content = await request('admin-content'); render(); }
function resetForm() { $('#event-form').reset(); $('#event-form [name=id]').value = ''; $('#form-title').textContent = 'Ajouter une date'; $('#cancel-edit').hidden = true; $('#event-error').textContent = ''; }
async function init() {
  try { const me = await request('me'); if (!me.authenticated) return; csrf = me.csrf; $('#login-view').hidden = true; $('#admin-view').hidden = false; await load(); } catch (_) {}
}
$('#login-form').addEventListener('submit', async event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); try { const result = await request('login', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(data) }); csrf = result.csrf; $('#login-view').hidden = true; $('#admin-view').hidden = false; await load(); } catch (error) { $('#login-error').textContent = error.message; } });
$('#event-form').addEventListener('submit', async event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); data.featured = $('#event-form [name=featured]').checked; try { await request('event', { method: data.id ? 'PUT' : 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(data) }); resetForm(); await load(); } catch (error) { $('#event-error').textContent = error.message; } });
$('#events').addEventListener('click', async event => { const id = event.target.dataset.edit || event.target.dataset.delete; if (!id) return; const item = content.events.find(value => value.id === id); if (event.target.dataset.edit) { Object.entries(item).forEach(([key,value]) => { const input = $(`#event-form [name="${key}"]`); if (input) input.type === 'checkbox' ? input.checked = Boolean(value) : input.value = value || ''; }); $('#form-title').textContent = 'Modifier une date'; $('#cancel-edit').hidden = false; window.scrollTo({top:0,behavior:'smooth'}); } else if (confirm(`Supprimer « ${item.titleFr} » ?`)) { try { await request('event', { method:'DELETE', headers:{'Content-Type':'application/json'}, body:JSON.stringify({id}) }); await load(); } catch (error) { alert(error.message); } } });
$('#cancel-edit').addEventListener('click', resetForm);
function savePageContent() { return request('page-content', { method:'PUT', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ creations:content.creations || [], collectivePhotos:content.collectivePhotos || [], mediationHosts:content.mediationHosts || [] }) }); }
function resetCreation() { $('#creation-form').reset(); $('#creation-form [name=id]').value = ''; $('#cancel-creation').hidden = true; $('#creation-error').textContent = ''; }
$('#creation-form').addEventListener('submit', async event => { event.preventDefault(); const form = Object.fromEntries(new FormData(event.target)); form.photos = form.photos.split('\n').map(x => x.trim()).filter(Boolean); if (!/^[a-z0-9-]+$/.test(form.slug)) { $('#creation-error').textContent = 'Le slug ne peut contenir que des minuscules, chiffres et tirets.'; return; } form.id = form.id || crypto.randomUUID(); const items = content.creations || []; const index = items.findIndex(item => item.id === form.id); if (index >= 0) items[index] = form; else items.push(form); content.creations = items; try { content = await savePageContent(); resetCreation(); render(); } catch (error) { $('#creation-error').textContent = error.message; } });
$('#creations-admin').addEventListener('click', async event => { const id = event.target.dataset.creationEdit || event.target.dataset.creationDelete; if (!id) return; const item = (content.creations || []).find(value => value.id === id); if (event.target.dataset.creationEdit) { Object.entries(item).forEach(([key,value]) => { const input = $(`#creation-form [name="${key}"]`); if (input) input.value = Array.isArray(value) ? value.join('\n') : value || ''; }); $('#cancel-creation').hidden = false; $('#creation-form').scrollIntoView({behavior:'smooth'}); } else if (confirm(`Supprimer « ${item.titleFr} » ?`)) { content.creations = content.creations.filter(value => value.id !== id); try { content = await savePageContent(); render(); } catch (error) { alert(error.message); } } });
$('#cancel-creation').addEventListener('click', resetCreation);
$('#shared-form').addEventListener('submit', async event => { event.preventDefault(); const form = Object.fromEntries(new FormData(event.target)); content.collectivePhotos = form.collectivePhotos.split('\n').map(x => x.trim()).filter(Boolean); content.mediationHosts = form.mediationHosts.split('\n').map(x => x.trim()).filter(Boolean); try { content = await savePageContent(); $('#shared-error').textContent = ''; render(); } catch (error) { $('#shared-error').textContent = error.message; } });
$('#upload-form').addEventListener('submit', async event => { event.preventDefault(); try { await request('upload', { method:'POST', body:new FormData(event.target) }); event.target.reset(); $('#upload-error').textContent = ''; await load(); } catch (error) { $('#upload-error').textContent = error.message; } });
$('#logout').addEventListener('click', async () => { await request('logout', {method:'POST'}); location.reload(); });
init();
