name: Deploy to OVH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Deploy WEBSITE to OVH
        env:
          OVH_HOST: ${{ secrets.OVH_HOST }}
          OVH_USERNAME: ${{ secrets.OVH_USERNAME }}
          OVH_PASSWORD: ${{ secrets.OVH_PASSWORD }}
        run: |
          lftp <<EOF
          set cmd:trace yes
          set net:timeout 20
          set net:max-retries 2
          set sftp:auto-confirm yes
          open -p 22 -u "$OVH_USERNAME","$OVH_PASSWORD" sftp://$OVH_HOST
          pwd
          ls
          cd www
          mirror --reverse --delete --verbose WEBSITE/ .
          bye
          EOF